### ISSUE TITLE
Make connectors pluggable

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors#1434]
### Problem Description

Problem: we always serve all connectors in our connector host. Even if some of them are turned off and do not occupy memory, we still need to install all libs and requirements for all connectors to run any single connector. 

It's problematic as some connector dependencies might rely on drivers/OS packages that are impossible to install in a uniform way in all OS's. We want to avoid that - existance of MSSQL connector that needs Kerberos driver should not require users to install Kerberos driver to run MongoDB connector.

### Proposed Solution

Investigate how to make pluggable connector system - only connectors that are running need to be installed.

Ideally, we need to make the host independent from the connectors - connectors can be a python package or a git repository, that we can pull and install in the host based on host configuration.

### Alternatives

To be researched. One obvious alternative is to always distribute a Docker image - this will eliminate a need for users to install anything, but brings a hard dependency on docker.

### Additional Context
See issue:  https://github.com/elastic/connectors-python/issues/1310

**Comment by wangch079** [comment]
Hi @elastic/ingestion-team, I chose this as my space-time project and here are some findings:

First of all, This applies to connector clients only. For cloud deployment, we should at least install all the dependencies of native connectors. Currently, we will install everything even if it's required by a connector client. This is one of the possible improvements, but I think that deserves a separate issue.

Officially, as of 8.9, we have 2 ways to [deploy self-managed connector](https://www.elastic.co/guide/en/enterprise-search/current/build-connector.html#build-connector-service):

1. [Run the code from source](https://www.elastic.co/guide/en/enterprise-search/current/build-connector.html#build-connector-service-source)
2. [Run from a Docker container](https://www.elastic.co/guide/en/enterprise-search/current/build-connector.html#build-connector-service-docker)
3. Possibly the 3rd option, [install via pip](https://github.com/elastic/connectors-python/issues/1490)

For all of the options, the connector service is installed first, and then run against a config file, which means we have to pack the dependencies of all connectors when we install it (1, `make install`, 2, `docker build`, 3, `pip install connector-service`), because we never know which connector this connector service will run against.

I'd like to discuss this with the team for other options, but I don't think it's the best time this week. I will pause the issue for now, and look for another topic.

**Comment by wangch079** [comment]
Hi @artem-shelkovnikov , do you think we should continue this ticket? As I mentioned above, the software is first built, then run, and we only know what connectors are configured when running the software. Let me know if I misunderstood.

**Comment by artem-shelkovnikov** [comment]
@wangch079 I'm not sure, need to check priorities with @danajuratoni and @DianaJourdan.

For us this ticket came out of the problem, that if we support Kerberos auth, then we'll need Kerberos installed for every user of connectors - that does not work for us and we wanna work around it if possible.

**Comment by wangch079** [comment]
I think we can close this ticket. With the current design, we will only know what connectors we need when we run the service.

I think a better approach to make connectors pluggable (inspired by AirByte), is to decouple the framework and data source implementations:

1. We can extract all the data source implementations into a separate repo, and publish it as a package in pypi.org. 
2. Similar to AirByte, the package will provide general functions to list available data sources
3. The data source should have a clearly defined contract, e.g. you need to provide `configuration` to instantiate a data source, you need to call `get_docs` to run a full sync.
4. The framework will be only in charge of scheduling/executing sync jobs. It will install the data source package as a dependency. 

WDYT?

**Comment by wangch079** [comment]
Anyway, will close this ticket now

**Comment by artem-shelkovnikov** [comment]
Yeah good call to close it for now, we can re-visit later
