### ISSUE TITLE
[Google Drive] Service account needs Editor permissions for sync

### ISSUE THREAD

**Issue by llermaly** [elastic/connectors#1474]
### Problem Description

The Service account needs editor permissions to be able to sync files. I don't think we should be asking for editor permissions if we are only going to read the files.

This is problematic because if we are using a group then we must give Editor permissions to the entire group.

This is related to #1473 , if you give "View" permission to the service account the sync will crash.

### Proposed Solution
Only require "View" permissions to sync the files.

### Additional Context
![CleanShot 2023-08-16 at 18 49 11](https://github.com/elastic/connectors-python/assets/8575569/a51767a1-f9cc-4bfb-850b-4be5468b236f)

**Comment by jedrazb** [comment]
Update: For files on shared drives we are able to list all permissions using the [permissions.list](https://developers.google.com/drive/api/reference/rest/v3/permissions/list) endpoint - that works only for shared drives.

For other "drives" e.g. `my drive`, `shared with me` - permissions are returned as a part of response in [files.list](https://developers.google.com/drive/api/reference/rest/v3/files/list) but the permissions are only populated if the requesting user (here SA) can further share the file (search for phrase `Output only. The full list of permissions for the file. This is only available if the requesting user can share the file. Not populated for items in shared drives.` in [REST Resource: files](https://developers.google.com/drive/api/reference/rest/v3/files))

So as for me, we are correctly handling both cases (shared and non-shared drives), and the viewer permission for non-shared drives doesn't return permissions as expected (since view-only permissions probably doesn't grant sharing rights).

**Comment by llermaly** [comment]
@jedrazb thanks! 

How this behave for domain-wide strategy using admin account? can see everything? or still needs to be shared with the admin?

**Comment by seanstory** [comment]
@jedrazb is this issue still relevant?

**Comment by jedrazb** [comment]
No longer relevant. Google Drive connector now supports using a domain-wide delegation for syncing data. For anyone reading this issue refer to: https://www.elastic.co/guide/en/enterprise-search/current/connectors-google-drive.html
