### ISSUE TITLE
GCS and ABS Cannot skip buckets if it doesn't have access

### ISSUE THREAD

**Issue by wangch079** [elastic/connectors#1831]
## Bug Description
The connector doesn't exclude buckets it doesn't have access to. When a connector is configured it tries to list all the buckets which are available for the service account. However, the service account might not have read access to some of the buckets. In this case, the sync job will fail.

### To Reproduce

1. Create a GSC connector.
2. Create a couple of buckets and deny access to one.
3. Run a sync job.
4. See the error.

## Expected behavior

When indexing "all buckets", skip buckets that are unavailable for the configured user and allow the sync job to keep running.

## Environment

8.11

## Additional context

[Slack message](https://elastic.slack.com/archives/C01795T48LQ/p1696292757222859)

**Comment by parth-elastic** [comment]
Hey @wangch079 , As per the earlier implementation in the framework, we used to follow a practice (overall for all the connectors) of raising an error for such cases which are inaccessible OR the limitations from the source API.
Similar to GCS in Azure blob storage connector also we are raising the exception if inaccessible bucket found.

We can take the enhancement to change the implementation to skip the buckets instead of showing the error for all the connector to unify the approach. 
Can we please change the label of this issue to Enhancement, as if we need to make it generic/unify across all the connector we need to update it for the older connectors.

cc: @danajuratoni @DianaJourdan

**Comment by danajuratoni** [comment]
@parth-elastic as discussed today, changing this to enhancement and adding it to be worked on next

**Comment by akanshi-elastic** [comment]
Progress Summary[24th nov- 30th nov]
GCS and ABS
1. Start Implementing: GCS and ABS Cannot skip buckets if it doesn't have access
2. raise PR for skipping access related error

**Comment by akanshi-elastic** [comment]
Progress Summary[1stdec- 6th dec]
GCS and ABS
1. Raise PR for skipping access related error
2. Start implementation for adding new RCF for passing buckets name.

**Comment by akanshi-elastic** [comment]
Progress Summary[7thdec- 14th dec]
GCS and ABS

1. Raise PR for adding new RCF for passing buckets name.
2. Address comments for same PR

**Comment by akanshi-elastic** [comment]
Hey @leemthompo Can you please modify the documentation for GCS and ABS? We have added new field `containers` in ABS and `buckets`  in GCS.

**Comment by akanshi-elastic** [comment]
@danajuratoni we can close this issue as all the respective PR's has been merged. The Open PR  shown in the thread is not related to this issue. Hence I removed the issue link from this PR.

**Comment by akanshi-elastic** [comment]
Progress Summary[11thjan- 18th jan]
GCS and ABS
1. Address comments for adding new RCF PR for passing buckets name
2. PR merged to kibana repo
