### ISSUE TITLE
[Network Drive] Connector does not download documents from Windows SMB drives

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors#2122]
## Bug Description
Connector treats files from some Windows SMB drives as empty - `allocation_size` is reported as 0. On the other hand, these files are not empty. Seems like `allocation_size` is a bad metric to determine file size.

### To Reproduce
1. Set up an Windows SMB drive somewhere on, for example, Windows Server 2016 and populate it with various files with various extensions
2. Run a sync against this drive
3. Check size and content of the documents
4. See that a lot of them have size = 0

## Expected behavior
Files are properly downloaded, and if possible, correctly report size

**Comment by praveen-elastic** [comment]
Did you face this in Windows Network Drive ? I am able to get expected behaviour in my Windows VM.

A quick search on internet highlights this issue in linux https://www.linuxquestions.org/questions/linux-networking-3/samba-truncating-files-to-0-bytes-275091/
Also, were these files populated using smb "put", since that was once a bug in linux https://bugzilla.samba.org/show_bug.cgi?id=5452

Some followup questions: 
1. Did you check the permissions are correct ?
2. Did you save and close the file before running the connector ?

**Comment by artem-shelkovnikov** [comment]
We were able to reproduce it against a real Windows SMB server on Windows Server 2016.

The problem was that a lot of files (all except *.xls) reported `allocation_size` as 0. User definitely had permissions to fetch the files and when we removed the constraint of "size>0" we got content of these files.
