### ISSUE TITLE
Report duplicate ids encountered by a sync

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors#2147]
### Problem Description

From time to time we see that the stats reported by connector differ from stats on index, connector can report it synced 100000 records, but index has 99998 records inside.

We need to have a mechanism that on connector side reports that the document was supposed to be inserted, but was updated instead.

### Proposed Solution
Needs research.

**Comment by DianaJourdan** [comment]
@artem-shelkovnikov just to clarify, there are 2 main reasons why the Doc count reported by connectors is different from the Docs added taken from the index:
1. it could be the case where connectors send a doc to ES and instead of being added, the document is found and it is updated
2. the connector sends a doc to ES and the insert fails, so it is not counted in the docs added

Is the goal of this ticket to change any of these 2 counters or to enhance logging, errors handling, so the end user has visibility on where the difference comes from?

**Comment by seanstory** [comment]
I'm planning on including counting duplicate Ids in https://github.com/elastic/connectors/issues/2317, so I'm going to close this issue in favor of that one.
