### ISSUE TITLE
Scheduled sync jobs trigger once per availability zone

### ISSUE THREAD

**Issue by gcasar** [elastic/connectors#2351]
## Bug Description
When using the connectors scheduling functionality several Scheduled sync jobs are triggered each time.

### To Reproduce
1. Create a Connector (reproduced with Github, Confluence and Jira)
2. Setup a scheduled sync, ex: once per day at 4AM
3. Multiple Scheduled sync jobs get triggered

## Expected behavior
A single scheduled job should get kicked off.

## Screenshots
Image 1: Connector configuration, note that this does not need to match exactly, even hourly syncs behave the same way
![image](https://github.com/elastic/connectors/assets/2477157/6d0a39ce-66d0-400f-acd1-d3c324c2266c)

Image 2: Log output (time difference is likely due to my local UTC+2 CEST timezone)
![image](https://github.com/elastic/connectors/assets/2477157/d765ec52-7c0a-4847-bbd4-45230c424c2b)

Image 3: UI after the job has been kicked-off
![image](https://github.com/elastic/connectors/assets/2477157/30d931fe-f2f7-4b01-9eec-67ac0f262fac)

## Environment
- Elastic Cloud
- Version: 8.13.1
- 4GB, 3AZ

## Additional context
Initially the bug was encountered when using 2AZs where duplicate sync jobs were triggered. When we switched to 3AZs the amount of sync jobs scheduled goes up to 3. If we view the details of the logs from image 2 all of them are kicked off on different instances.

If I scale down to one AZ the symptoms go away.

**Comment by seanstory** [comment]
thanks for filing @gcasar !

Can you provide some more details - did you encounter this using Elastic Cloud, or were you self-managing the connectors across multiple AZs?

And is this specific to different AZs, or are you seeing this also if you had several connectors services deployed in the same AZ?

**Comment by Jsasres** [comment]
@seanstory I can answer the first part, this is all running in ES Cloud.

**Comment by gcasar** [comment]
@seanstory this is all part of the Elastic Cloud offering with zero non-managed connector services (where I'm assuming you mean non-native connectors configured against that instance).

**Comment by seanstory** [comment]
Ok perfect, thanks for confirming.

**Comment by artem-shelkovnikov** [comment]
Small triaging with @wangch079 had the following outcome:

1. Concurrency control as a feature works - we don't have problem with multiple services picking up same job at the same time, so problem is in this particular place
2. Most likely the problem happens when we're checking that the job should be scheduled [here](https://github.com/elastic/connectors/blob/main/connectors/services/job_scheduling.py#L191-L237).
It feels like the problem happens with determining when the sync should be scheduled and there's an edge case that happens after a [fix was done to stop skipping sync jobs](https://github.com/elastic/connectors/pull/1689)

I managed to at least confirm that this problem is pretty consistent and indeed happens due to the above piece of code. What's missing now is more logging (last_sync_scheduled_at is not logged and is critical to have a reproducible use-case).

Current theory is that this change will fix it:

```
            if (
                last_sync_scheduled_at is not None
-               and last_sync_scheduled_at > this_wake_up_time
+              and last_sync_scheduled_at > last_wake_up_time  # We need to check that it was not scheduled after we woke up last time, not this time
            ):
```
