### ISSUE TITLE
[google_drive] Cannot connect to host host.docker.internal:9200

### ISSUE THREAD

**Issue by Sagar-AArya** [elastic/connectors#2385]
## Bug Description
I'm trying to run google_drive connector client through docker on my Windows machine. When its trying to connect to elasticsearch getting below error.

[FMWK][12:08:46][ERROR] Could not connect to the server
[FMWK][12:08:46][ERROR] Cannot connect to host host.docker.internal:9200 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]
[FMWK][12:09:50][CRITICAL] https://host.docker.internal:9200 seem down. Bye!

### To Reproduce
1. I have followed this documentation to run Elasticsearch, Kibana and Enterprisesearch - [docker-compose-example](https://www.elastic.co/guide/en/enterprise-search/current/docker.html#docker-compose-example). I'm able to access the Kibana and configure google_drive connector.
2. I have followed this documentation to run the connector client (https://github.com/elastic/connectors/blob/8.13/docs/DOCKER.md)

## Expected behavior
The connector container should start successfully and I should be able to connect to this container from Kibana.

## Environment

- OS: Windows11
- Java: 22
- Docker Engine: v24.0.2

## Attached My Docker compose yml and Connector config yml

[docker-compose.txt](https://github.com/elastic/connectors/files/14958993/docker-compose.txt)
[connector_config.txt](https://github.com/elastic/connectors/files/14958998/connector_config.txt)

## Connector client docker run command
`docker run -v C:\Users\Sagar\Desktop\elastic\config:/configuration --network "elastic_docker_default" --tty --rm docker.elastic.co/enterprise-search/elastic-connectors:8.13.1.0 /app/bin/elastic-ingest -c /configuration/config.yml`

I have tried with https://localhost:9200, https://myIp:9200 as host but nothing worked.

![image](https://github.com/elastic/connectors/assets/14965262/8c346a8f-c8cc-4b85-8b48-2cc9cd13a2d8)

Thanks in advance.

**Comment by seanstory** [comment]
Hi @Sagar-AArya  - this looks like it might be a documentation gap. `host.docker.internal` is a default name for Mac Docker Desktop, but for other docker providers a little extra is necessary. Lots of ways to do this here. You can provide "extra hosts" to tell connectors that `host.docker.internal` has meaning:

```
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

Or you can run in a specific network mode, and use `localhost` instead of `host.docker.internal` like:

```
    network_mode: "host"
```

You could also modify the first docker compose file you shared to use a consistent network that the connectors command can also use.

**Comment by Sagar-AArya** [comment]
Hi @seanstory 

Thanks for the quick response. I have tried one of the solution you provided. But that didn't work..
This is how I changed my config.yml
`
elasticsearch.host: https://host.docker.internal:9200
elasticsearch.api_key: "MWdfN3g0NEJCWkhQeTB6bzhiZnQ6LUFnaVU5b29RbldvMjlEM1ZBbloyQQ=="

connectors:
  - connector_id: "1Q_7x44BBZHPy0zoobcM"
    service_type: "google_drive"
    api_key: "MWdfN3g0NEJCWkhQeTB6bzhiZnQ6LUFnaVU5b29RbldvMjlEM1ZBbloyQQ=="
    extra_hosts:
      - "host.docker.internal:host-gateway"
`

Is this what you suggested? or am I missing something !

**Comment by Sagar-AArya** [comment]
@seanstory 

Also, If I have to use a specific network_mode.. Can you confirm these are the things I have to do?

1. Add network_mode:host in all services in docker_compose.
2. Update the connector config.yml to have elasticsearch.host:https://localhost:9200
3. When starting the connector client using docker pass --net="host" flag(or is it --network?)

**Comment by seanstory** [comment]
> Is this what you suggested?

Sorry, no I think you misunderstood. the 
```
  extra_hosts:
    - "host.docker.internal:host-gateway"
```
Is a docker configuration. I shared the docker-compose syntax, but looking back at your message, you're not using docker-compose for running connectors, but `docker run`, so for you the syntax would be:

```
docker run \
-v ~/connectors-config:/config \
--network "elastic" \
--tty \
--rm \
--add-host "host.docker.internal:host-gateway" \
docker.elastic.co/enterprise-search/elastic-connectors:<VERSION>-SNAPSHOT \
/app/bin/elastic-ingest \
-c /config/config.yml
```

where `--add-host "host.docker.internal:host-gateway"` is the new bit.


> Also, If I have to use a specific network_mode.. Can you confirm these are the things I have to do?
> 1. Add network_mode:host in all services in docker_compose.

No, if Kibana's working, then it's already able to talk to Elasticsearch, and your browser can talk to it, so no need to change the networking for those.

> 2. Update the connector config.yml to have elasticsearch.host:https://localhost:9200/

Yes

> When starting the connector client using docker pass --net="host" flag.

Yes. Again, my mistake, I'd originally shared the docker-compsose syntax for `network_mode: "host"` but with `docker run` it would be `--net=host` as you say. This is the alternative to using `--add-host "host.docker.internal:host-gateway"` as described above.

**Comment by Sagar-AArya** [comment]
Hi @seanstory 

I have tried both the solutions still no luck.

This is what I got if I try with --net flag..
![Screenshot (292)](https://github.com/elastic/connectors/assets/14965262/c2280115-828b-4875-9adb-88f261d52e7e)
![Screenshot (293)](https://github.com/elastic/connectors/assets/14965262/6c585792-c840-49fb-8128-840af7b26961)

**Comment by seanstory** [comment]
I'd missed this previously, but I see with both approaches you're using `https`. Which makes me think that the `--add-hosts` approach is actually working, because it's not telling you it can't connect, but that the certificate validation is failing.

Looking at the [docker compose example you're using](https://www.elastic.co/guide/en/enterprise-search/current/docker.html#docker-compose-example) for standing up Elasticsearch, you're going to need to run connectors such that they also have access to the certificates volume, and you'll need to modify your connector config.yml to specify these SSL settings:

https://github.com/elastic/connectors/blob/0d35433d418427a8ee4d991bbc36d5ec3e07665d/config.yml.example#L53-L58

**Comment by Sagar-AArya** [comment]
@seanstory 

Thanks again for the response.. Just a clarification..

I have to generate the required certs(https://docs.confluent.io/kafka-connectors/elasticsearch/current/security.html#step-2-generate-certificates) and pass that path to ca_certs right?

If that's yes then
Do I also need to update :
`volumes:
      - certs:/usr/share/kibana/config/certs`
for the services in my docker_compose.yml(which I'm using to run ES, Kibana and EnterpriceSearch) ?

**Comment by jedrazb** [comment]
> I have to generate the required certs(https://docs.confluent.io/kafka-connectors/elasticsearch/current/security.html#step-2-generate-certificates) and pass that path to ca_certs right?

HI @Sagar-AArya From the docs that you are following we have: The `--volume` argument mounts a volume within the container. Elasticsearch will write a certificate file to this volume on startup. The Enterprise Search container will mount the same volume in order to read the certificate file. 

This docker compose already creates and manages certificates for you. You would need to attach `certs` volume to connector service started via `docker run` and point the service config to the certificate from the attached docker volume. 

For initial local development it might make sense to temporarily disable SSL to check if services can talk to each other, once you get that setup right, that the next step would be to enable SSL. In that case you might need to edit ES configs in docker compose to:
```
     - xpack.security.enabled=false
     - xpack.security.http.ssl.enabled=false
```
The you can point connector service to `http://localhost:9200` and test if your setup works. Note, this suggestion is for testing local setup only, please always enable security and SSL in prod.

**Comment by Sagar-AArya** [comment]
@jedrazb 

This docker compose already creates and manages certificates for you. You would need to mount certs volume to connector service started via docker run and point the service config to the certificate from the attached docker volume.

I see the certs path in es service in docker compose file - /usr/share/elasticsearch/config/certs.

Here's what I did..

I changed the connector service docker run command to have --volume es01-1:/usr/share/elasticsearch/config/certs

`docker run -v C:\Users\Sagar\Desktop\elastic\config:/configuration --volume es01-1:/usr/share/elasticsearch/config/certs --add-host="host.docker.internal:host-gateway" --tty --rm docker.elastic.co/enterprise-search/elastic-connectors:8.13.1.0 /app/bin/elastic-ingest -c /configuration/config.yml`

I also updated the config.yml to have - ca_certs: "/usr/share/elasticsearch/config/certs"

Still no luck, am I missing something?

**Comment by seanstory** [comment]
> Still no luck, am I missing something?

Yes. The relevant parts from the Docker Compose example are:
```
volumes:
      - certs:/usr/share/elasticsearch/config/certs
```
and
```
volumes:
  certs:
    driver: local
```

This says, "There is a local dir, `./certs/`, that you can map to the docker container for Elastcsearch at `/usr/share/elasticsearch/config/certs`

So what you need to do now with _connectors_ is make sure that when it runs, it also mounts that local `certs/` dir _somewhere_ on the connectors container with a docker volume, AND that the connector config.yml references the container path to that dir.

Without knowing what directories you're running which commands to, I can't give you the exact right paths. But I expect that your `--volume es01-1:/usr/share/elasticsearch/config/certs` is not right, since it should be `--volume /path/to/local/certs:/path/to/connector/containter/certs` and then your yaml would need to have `ca_certs: "/path/to/connector/container/certs"` 

I think it's unlikely that `es01-1` is a local dir name, or that `/usr/share/elasticsearch` is a valid path in your connector container.

**Comment by Sagar-AArya** [comment]
Hi @seanstory 

I have not seen the certs directory on my machine. I changed the local path.
Here's what I did.
1. I updated the `certs:/usr/share/elasticsearch/config/certs` to `C:/xampp/htdocs/CloudWave/Projects/elastic_docker/es_certs:/usr/share/elasticsearch/config/certs` for all the services in my docker compose file.
2. I have also updated `volumes:
  certs:` to ```
volumes:
  es_certs:
```
3. I have changed my connector client docker run command to have `--volume C:\xampp\htdocs\CloudWave\Projects\elastic_docker\es_certs:/certs`. So, now the command looks like - `docker run -v C:\Users\Sagar\Desktop\elastic\config:/configuration --volume C:\xampp\htdocs\CloudWave\Projects\elastic_docker\es_certs:/certs --add-host="host.docker.internal:host-gateway" --tty --rm docker.elastic.co/enterprise-search/elastic-connectors:8.13.1.0 /app/bin/elastic-ingest -c /configuration/config.yml`
4. In my connector config yml I updated the ca_certs to `ca_certs: "/certs"`

I'm able to see all the certificates related files created under C:\xampp\htdocs\CloudWave\Projects\elastic_docker\es_certs folder but the still the I'm not able to connect to elasticsearch.

Attached the screenshots for reference.
![Screenshot (295)](https://github.com/elastic/connectors/assets/14965262/413f6463-4d26-46d9-b026-45588072286c)
![Screenshot (296)](https://github.com/elastic/connectors/assets/14965262/b7af7f99-bda4-42c2-ae1b-b03ac86f9986)
![Screenshot (297)](https://github.com/elastic/connectors/assets/14965262/002f05c2-df6c-4b3a-bce1-8c6bb00d75e7)

**Comment by Sagar-AArya** [comment]
Hi @jedrazb 

I have logged into the container.
1. cert files are there.
2. I am able to successfully run the curl command.

![image](https://github.com/elastic/connectors/assets/14965262/35599ec9-5ab3-4b37-b0b8-7bbfac0c0739)

**Comment by seanstory** [comment]
This is helpful. Can you try changing `ca_certs: "/certs"` to `ca_certs: "/certs/ca" in your connector config.yml?

**Comment by Sagar-AArya** [comment]
Hi @seanstory 

I have tried that but still same issue.

**Comment by jedrazb** [comment]
I recreated your setup locally, this worked for me :) Note, the certificate is only valid for `localhost:9200`

```
connectors:
  - connector_id: "g-drive"
    service_type: "google_drive"
    api_key: ***
elasticsearch:
  host: "https://localhost:9200"
  api_key: ***

#  Whether SSL is used for the Elasticsearch connection.
elasticsearch.ssl: true

#  Path to a CA bundle
elasticsearch.ca_certs: /certs/ca/ca.crt

service.log_level: DEBUG
```

**Comment by Sagar-AArya** [comment]
@jedrazb 

Thank you so much. It worked for me.
![image](https://github.com/elastic/connectors/assets/14965262/12ae1461-61a6-4794-89b8-daec94b9983c)

**Comment by seanstory** [comment]
Excellent! Since it's working as expected, I'm going to close this issue but may follow some follow-ups to try to make this more simple going forward. @jedrazb the above PR is a great step towards improving this experience! 👏

**Comment by jedrazb** [comment]
@leemthompo tagging after our docs discussion
