### ISSUE TITLE
Error while synchronizing Projects from Jira - mapper [Project.versions.name] cannot be changed from type [text] to [date]

### ISSUE THREAD

**Issue by dodie** [elastic/connectors#2501]
## Bug Description
When I run a full sync from Jira Data Center, the synchronization job completes successfully, but in the logs of the connector the following error message appears:

```
[FMWK][07:55:13][ERROR] [Connector id: ..., index name: jira, Sync job id: ...] operation index failed, {'type': 'illegal_argument_exception', 'reason': 'mapper [Project.versions.name] cannot be changed from type [text] to [date]'}
[FMWK][07:55:13][ERROR] Exception found for task Task-306: mapper [Project.versions.name] cannot be changed from type [text] to [date]
NoneType: None
```

### To Reproduce

1. Set up a connector to Jira Data Center. In Jira, set up a project with a version with the following name: `2023-02`.
2. Start a full synchronization.
3. Wait, until the full synchronization finishes.
4. Investigate the logs of the connector.

## Expected behavior
After the synchronization job finishes, the projects should be synchronized to Elasticsearch without an error.

## Environment
- OS: RHEL8, connector is run in a Docker container
- Connector Framework: enterprise-search/elastic-connectors: 8.13.2.1.
- Stack version: 8.13.2

**Comment by moxarth-elastic** [comment]
@dodie when documents gets indexed at the first time, elastic search prepares the schema based on it. Now, if the datatype of any field will change, elastic will raise an error for that. 

Since, we're indexing the entire API response for all jira objects, we can't prevent this error one by one for all fields and we can't even index an entire response as a string o/w the user experience will become worse.

And this case looks different from others, because I've already tried to type caste it to string but elastic search treats it as a date at the time of indexing. Since the date/datetime comes inside quotes from the response, we know it is a string but elastic search recognises it as a date/datetime.

**Comment by moxarth-elastic** [comment]
@dodie the framework handles the dynamic field mapping and due to auto detection of elastic search for the dates fields, you need to update the schema manually for now.
You can create a new index and hit the following command:
```
PUT /your-index/_mapping
{
  "date_detection": false
}
``` 
Now, you can start syncing the data.
for reference: https://stackoverflow.com/questions/43734808/how-to-make-elasticsearch-treat-keyword-as-string-not-date

**Comment by moxarth-elastic** [comment]
@dodie did you get a chance to try the above solution?

**Comment by dodie** [comment]
Hi @moxarth-elastic , yes, it works! Thank you for the details, now I see, it indeed makes sense not trying to handle all the mapping of the individual (and custom) fields in the connector, but let Elasticsearch do it.
