### ISSUE TITLE
[mysql-connector] Can't connect to MySQL server on 'localhost'

### ISSUE THREAD

**Issue by Sagar-AArya** [elastic/connectors#2544]
## Bug Description
I'm trying to run mysql connector client through docker on my Windows machine. The connector connection is successful but when I'm trying to sync the data. Its giving me an error.

### To Reproduce
1. I have followed this documentation to run Elasticsearch, Kibana and Enterprisesearch - [docker-compose-example](https://www.elastic.co/guide/en/enterprise-search/current/docker.html#docker-compose-example). I'm able to access the Kibana and configure google_drive connector.
2. I have followed this documentation and also instructions from Kibana UI to run the connector client (https://github.com/elastic/connectors/blob/8.13/docs/DOCKER.md)

## Expected behavior
The connector container should sync the data from Database.
I cross checked my MySQL connection details. They are all correct.

## Screenshots
![image](https://github.com/elastic/connectors/assets/14965262/00508012-606f-40a9-8b0b-c6139f8365cd)
![image](https://github.com/elastic/connectors/assets/14965262/46a4edee-6ce5-4be6-8c41-b80e3cd4931f)
![image](https://github.com/elastic/connectors/assets/14965262/b9b2226f-7606-401e-872c-415e0251914c)

## Environment

- OS: Windows11
- Docker Engine: v24.0.2

## Additional context
Connector client docker run command is:
docker run -v C:\xampp\htdocs\CloudWave\Projects\elastic_docker\mysql_connector_config\config:/configuration --volume C:\xampp\htdocs\CloudWave\Projects\elastic_docker\es_certs:/certs --network host --tty --rm docker.elastic.co/enterprise-search/elastic-connectors:8.13.1.0 /app/bin/elastic-ingest -c /configuration/config.yml

**Comment by artem-shelkovnikov** [comment]
Hi @Sagar-AArya,

Can you verify that your docker container that hosts connectors has access to MySQL? Easiest way is SSH'ing into the container and running `telnet 127.0.0.1 3306`. My gut feeling says that it's not accessible, because docker container is isolated from your local environment.

You can try some of instructions from [this post](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach) and see if you can make your container access outside of the container.

**Comment by Sagar-AArya** [comment]
@artem-shelkovnikov 

Thank you. That worked.
