### ISSUE TITLE
Impossible to terminate running connector service from source

### ISSUE THREAD

**Issue by jedrazb** [elastic/connectors#2568]
### To Reproduce
1. Start `make run`
2. Do some syncs with connector configured
3. Try to terminate, sometimes you run into 
```
^C[12:08:30][INFO] Caught SIGINT. Graceful shutdown.
^C[12:18:37][INFO] Caught SIGINT. Graceful shutdown.
```

And the service doesn't terminate gracefully.

## Expected behavior

We should support graceful termination on  SIGINT

**Comment by seanstory** [comment]
@jedrazb what command did you use to start the container? I would expect `--tty -i` would ensure this works, and I haven't had any issue before.

**Comment by jedrazb** [comment]
> what command did you use to start the container? I would expect --tty -i would ensure this works, and I haven't had any issue before.

It was actually `make run` when running from source

**Comment by seanstory** [comment]
I'm going to close this, since it's not currently actionable. We've made a number of fixes recently around async, signal handling, and interrupting sleeps that have made this less common, but probably not totally "fixed." However, "fixing" it is going to be a long-term effort to find each edge case and address them one at a time, rather than a big-bang "fix."

**Comment by jedrazb** [comment]
That one was most likely related to the async implementation of github connector
