### ISSUE TITLE
Create symlink for old command `/app/bin/elastic-ingest`

### ISSUE THREAD

**Issue by jedrazb** [elastic/connectors#2886]
### Problem Description

For 8.16 we moved the Python virtual env into the `.venv` folder. It means that the command `/app/bin/elastic-ingest` that is used in all of our Docker documentation breaks as the old path doesn't exist and the new command is now `/app/.venv/bin/elastic-ingest`. 

This can be particularly painful for folks who have their docker command crafted for running connectors on their own infra, and after migration to 8.16 it will simply stop working. 

We should:
- Create symlink from old command `/app/bin/elastic-ingest` to new command `/app/.venv/bin/elastic-ingest` - to ensure backward compatibility and smooth migration experience
- Update docs everywhere (do we need it with symlink?):
  - Including this repo `DOCKER.md`
  - Elastic docs 
  - Kibana autogenerated commands to start docker connectors 
- (?) Does `/app/.venv/bin/elastic-ingest` command look good? Perhaps we should even consider a shorter command to start the service so that the docker run command is less overwhelming

**Comment by amrohendawi** [comment]
this issue still occurs when I try to run the elasticsearch connector service by following the instructions on the screen:

![Image](https://github.com/user-attachments/assets/3bb6985f-1c0f-4443-9824-84d602bf2090)

There are 2 issues here:

## 1. docker is unable of finding the connector docker image:
  ```bash
  docker run \
-v "$HOME/elastic-connectors:/config" \
--tty \
--rm \
docker.elastic.co/enterprise-search/elastic-connectors:8.15.0 \
/app/bin/elastic-ingest \
-c /config/config.yml
Unable to find image 'docker.elastic.co/enterprise-search/elastic-connectors:8.15.0' locally
docker: Error response from daemon: manifest for docker.elastic.co/enterprise-search/elastic-connectors:8.15.0 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

to solve this I went to the [registry page](https://www.docker.elastic.co/r/enterprise-search/elastic-connectors) and manually chose an image

## 2. docker is unable of finding `/app/bin/elastic-ingest``

when I run:

```bash
docker run \
-v "$HOME/elastic-connectors:/config" \
--tty \
--rm \
docker.elastic.co/enterprise-search/elastic-connectors:sha256-fe2becf698b8dafb8cfbe62b81989ca75f70c8f759ee2e37dc4ba4b8f3db6f9a \
/app/bin/elastic-ingest \
-c /config/config.yml
```

I get the error

```bash
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/bin/elastic-ingest": stat /app/bin/elastic-ingest: no such file or directory: unknown.
```

That's because `elastic-ingest`is actually inside `/app/.venv/bin/elastic-ingest`

**Comment by artem-shelkovnikov** [comment]
@amrohendawi first bug that you've reported should be fixed in later versions.

Re: docker image. We don't recommend using docker images with SHA versions - you can consider these nightly images. Please use versioned ones (in your example it would be `docker.elastic.co/enterprise-search/elastic-connectors:8.15.0.0`
